# Use an official GCC image as the base image
FROM gcc:latest

ARG EXECUTABLE
ARG PROPERTY_FILE
ARG PORT

# Set the working directory
WORKDIR /app

ENV APP_EXECUTABLE=$EXECUTABLE

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

# Compile the C code
RUN gcc -Wall client.c properties.c -o $EXECUTABLE

# Define the command to run the client executable
CMD sh -c "$APP_EXECUTABLE $PROPERTY_FILE"
