# Use an official GCC image as the base image
FROM gcc:latest

ARG EXECUTABLE
ARG PROPERTY_FILE
ARG PORT

# Set the working directory
WORKDIR /app

ENV APP_EXECUTABLE=$EXECUTABLE

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

RUN chmod +x compile_client.sh
RUN ./compile_client.sh

RUN chmod +x run_client
RUN ./run_client

