# Use an official GCC image as the base image
FROM gcc:latest

ARG EXECUTABLE
ARG PROPERTY_FILE
ARG PORT

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

EXPOSE $PORT

# Compile the C code
RUN echo "Command: gcc -Wall server.c properties.c -o $EXECUTABLE -pthread"
RUN gcc -Wall server.c properties.c -o $EXECUTABLE -pthread
#RUN chmod +x $EXECUTABLE

# Define the command to run the client executable
#CMD sh -c "$EXECUTABLE $PROPERTY_FILE"
