# Use an official GCC image as the base image
FROM gcc:latest

ARG EXECUTABLE
ARG PROPERTY_FILE
ARG PORT

ENV APP_EXECUTABLE=$EXECUTABLE

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /usr/src/myapp
COPY . .

EXPOSE $PORT

# Compile the C code
RUN echo "Command: gcc -Wall server.c properties.c -o $EXECUTABLE -pthread"
RUN gcc -Wall server.c properties.c -o $APP_EXECUTABLE -pthread

# Run the file
    # NOTE: property file doesnt do anything, is hard coded, need to fix this
CMD sh -c "$APP_EXECUTABLE $PROPERTY_FILE"
