# Use an official GCC image as the base image
FROM gcc:latest

# Define arguments
ARG SERVERFILE
ARG APP_EXECUTABLE
ARG PORT
ARG DEFINE_DBG

ENV APP_EXECUTABLE=$APP_EXECUTABLE

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY server/app .

# Compile the C code with condition for debug
RUN if [ $DEFINE_DBG == 1 ]; then \
        echo "Building in debug mode"; \
        gcc -Wall $SERVERFILE properties.c -o $APP_EXECUTABLE -pthread -DPORT=$PORT -DDBG; \
    else \
        echo "Building in release mode"; \
        gcc -Wall $SERVERFILE properties.c -o "$APP_EXECUTABLE" -pthread -DPORT=$PORT; \
    fi

# Run the executable
RUN echo "Running app: $APP_EXECUTABLE"
CMD sh -c "./${APP_EXECUTABLE}"
